## Site details
site_name: 'computation wiki'
site_description: 'computational wiki from Ming (Tommy) Tang'
site_author: 'Ming Tang'
site_url: 'https://crazyhottommy.github.io/computation_wiki/'

repo_name: 'crazyhottommy/computation_wiki'
repo_url: 'https://github.com/crazyhottommy/computation_wiki'


nav:
    - Home: index.md
    - Computation Setup:
      - set up MacOS: setup/setup_macos.md
      - set up HPC accounts: setup/hpc-info.md
    - Working with Kraken:
      - mount kraken folder to local computer: kraken/kraken_sshfs.md
      - Run Rstudio on Kraken: kraken/kraken_rstudio.md
      - Run jupyter notebook: kraken/kraken_jupyter.md
    - Working with Google Cloud:
      - Getting Started with gcp: google-cloud/getting-started-with-google-cloud.md
      - Run WES on gcp: google-cloud/wes-gcp.md
      - WES ingestion on gcp: google-cloud/wes-ingestion.md
      - Run CHIPS on gcp: google-cloud/chips-gcp.md
      - Run CHIPS automator on gcp: google-cloud/chips-automator.md
      - Run TCR on gcp: google-cloud/tcr-gcp.md
      - Build Reference Snapshot: google-cloud/build-reference-snapshot.md
      - Build Image: google-cloud/build-new-image.md
      - Expand root partition: google-cloud/expand-partition.md
      - Common Q&A: google-cloud/common-questions.md
    - ATACseq pipeline:
      - Make bwa indices: atac/atac-bwa-reference.md
    - RIMA RNAseq pipeline:
      - Build RIMA references: RIMA/build-RIMA-reference.md
    - miscellaneous:
      - Making figures: miscellaneous/inkscape.md



## Copyright
copyright: 'Copyright &copy; 2020 <a href="https://divingintogeneticsandgenomics.rbind.io/">Ming Tang</a>'

## Configuration
theme:
  name: material
  language: 'en'
  palette:
    primary: 'Blue'
    accent: 'Blue'
  font:
    text: 'IBM Plex Sans'
    code: 'Fira Code'
#  logo: 'assets/images/logo.png'
#  favicon: 'assets/images/logo.png'
  feature:
    tabs: false

extra_css:
  - 'assets/css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css'

extra_javascript:
  - 'assets/js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js'


# Google Analytics
google_analytics:
  - ''
  - 'auto'

markdown_extensions:
  - admonition
  - fontawesome_markdown
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - meta
  - footnotes
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  # - pymdownx.arithmatex:
  #     generic: true

plugins:
  - search
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true
